package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8D4F00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC0)
val md_theme_light_onPrimaryContainer = Color(0xFF2D1600)
val md_theme_light_secondary = Color(0xFF735943)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC0)
val md_theme_light_onSecondaryContainer = Color(0xFF291706)
val md_theme_light_tertiary = Color(0xFF5A6238)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDEE8B2)
val md_theme_light_onTertiaryContainer = Color(0xFF181E00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201B17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201B17)
val md_theme_light_surfaceVariant = Color(0xFFF2DFD1)
val md_theme_light_onSurfaceVariant = Color(0xFF51443A)
val md_theme_light_outline = Color(0xFF837469)
val md_theme_light_inverseOnSurface = Color(0xFFFAEFE8)
val md_theme_light_inverseSurface = Color(0xFF352F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB877)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8D4F00)
val md_theme_light_outlineVariant = Color(0xFFD5C3B6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB877)
val md_theme_dark_onPrimary = Color(0xFF4B2700)
val md_theme_dark_primaryContainer = Color(0xFF6B3B00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC0)
val md_theme_dark_secondary = Color(0xFFE2C0A5)
val md_theme_dark_onSecondary = Color(0xFF412C19)
val md_theme_dark_secondaryContainer = Color(0xFF5A422D)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC0)
val md_theme_dark_tertiary = Color(0xFFC2CB98)
val md_theme_dark_onTertiary = Color(0xFF2C340E)
val md_theme_dark_tertiaryContainer = Color(0xFF424A23)
val md_theme_dark_onTertiaryContainer = Color(0xFFDEE8B2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201B17)
val md_theme_dark_onBackground = Color(0xFFECE0D9)
val md_theme_dark_surface = Color(0xFF201B17)
val md_theme_dark_onSurface = Color(0xFFECE0D9)
val md_theme_dark_surfaceVariant = Color(0xFF51443A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C3B6)
val md_theme_dark_outline = Color(0xFF9E8E82)
val md_theme_dark_inverseOnSurface = Color(0xFF201B17)
val md_theme_dark_inverseSurface = Color(0xFFECE0D9)
val md_theme_dark_inversePrimary = Color(0xFF8D4F00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB877)
val md_theme_dark_outlineVariant = Color(0xFF51443A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF442504)
